{% set version = "3.1.3" %}

package:
  name: cyclonedx-python-lib
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/c/cyclonedx-python-lib/cyclonedx_python_lib-{{ version }}.tar.gz
    sha256: 077894908b441a1a9ff84207fe3c84f1229b319564cbe83eb929e856cace3c02
  - folder: src
    url: https://github.com/CycloneDX/cyclonedx-python-lib/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 02d8097c48bd4d12222a6b38264445417aea9ccf8407f1d756b60f4e7e046451

build:
  number: 0
  noarch: python
  script:
    - cd dist && {{ PYTHON }} -m pip install . -vv
    - |-
      {{ PYTHON }} -c "(__import__('pathlib').Path(__import__('site').getsitepackages()[0]) / 'LICENSE').unlink()"

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6
  run:
    - python >=3.6
    # from poetry-generated setup.py
    - packageurl-python >=0.9
    - setuptools >=47.0.0
    - sortedcontainers >=2.4.0,<3.0.0
    - toml >=0.10.0,<0.11.0
    # :python_version < "3.8"
    - importlib-metadata >=3.4

test:
  source_files:
    - src/tests
    - src/cyclonedx/schema
  imports:
    - cyclonedx
  commands:
    # more in run_test.py
    - pip check
  requires:
    - ddt >=1.6.0,<2.0.0
    - jsonschema >=4.2.1
    - lxml >=4.7.0
    - pip
    - pytest-cov
    - tox
    - xmldiff

about:
  home: https://github.com/CycloneDX/cyclonedx-python-lib
  summary: A library for producing CycloneDX SBOM (Software Bill of Materials) files.
  license: Apache-2.0
  license_file: dist/LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
