{% set version = "3.1.4" %}

package:
  name: cyclonedx-python-lib
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cyclonedx-python-lib/cyclonedx_python_lib-{{ version }}.tar.gz
  sha256: 21f9991486c58833eb1903ae7d423d88f6bee51bf6a6322e7556dce83b895a27

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv
    - |-
      {{ PYTHON }} -c "(__import__('pathlib').Path(__import__('site').getsitepackages()[0]) / 'LICENSE').unlink()"

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6
  run:
    - python >=3.6
    # from poetry-generated setup.py
    - packageurl-python >=0.9
    - setuptools >=47.0.0
    - sortedcontainers >=2.4.0,<3.0.0
    - toml >=0.10.0,<0.11.0
    # :python_version < "3.8"
    - importlib-metadata >=3.4

test:
  imports:
    - cyclonedx
  source_files:
    - tests
  commands:
    - pip check
    - pytest -vv --cov=cyclonedx --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=91
  requires:
    - ddt >=1.6.0,<2.0.0
    - jsonschema >=4.2.1
    - lxml >=4.7.0
    - pip
    - pytest-cov
    - tox
    - xmldiff

about:
  home: https://github.com/CycloneDX/cyclonedx-python-lib
  summary: A library for producing CycloneDX SBOM (Software Bill of Materials) files.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
