{% set version = "0.11.1" %}

package:
  name: cyclonedx-python-lib
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/c/cyclonedx-python-lib/cyclonedx-python-lib-{{ version }}.tar.gz
    sha256: cb0f1730ebe23c37820a9a2d4b42fc1d19fb3e8e6e92dfd3489673c76152e43c
  - folder: src
    url: https://github.com/CycloneDX/cyclonedx-python-lib/archive/refs/tags/v{{ version }}.tar.gz
    sha256: dfb705e1e4a4e4426e6f057f57ead665d46df203106df4a9f2caf01c76c2fa43

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} {{ RECIPE_DIR }}/patch_meta.py
    - cd dist && {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6,<4.0
  run:
    - importlib-metadata >=4.8.1,<5.0.0
    - packageurl-python >=0.9.4,<0.10.0
    - python >=3.6
    - requirements-parser >=0.2.0,<0.3.0
    - setuptools >=50.3.2,<59
    - toml >=0.10.2,<0.11.0
    - types-setuptools >=57.4.2,<58.0.0
    - types-toml >=0.10.1,<0.11.0

test:
  source_files:
    - src/tests
  imports:
    - cyclonedx
  commands:
    - pip check
    - cd src/tests
    - pytest -vv --cov cyclonedx --cov-fail-under 92 --cov-report term-missing:skip-covered --no-cov-on-fail
  requires:
    - pip
    - pytest-cov
    - tox

about:
  home: https://github.com/CycloneDX/cyclonedx-python-lib
  summary: A library for producing CycloneDX SBOM (Software Bill of Materials) files.
  license: Apache-2.0
  license_file: dist/LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
