{% set version = "1.1.1" %}

package:
  name: cyclonedx-python-lib
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/c/cyclonedx-python-lib/cyclonedx-python-lib-{{ version }}.tar.gz
    sha256: 03f810246ee45d8a8027e5f159c13d67632ae5a8e2e1d143b1bcc28b8b98b9eb
  - folder: src
    url: https://github.com/CycloneDX/cyclonedx-python-lib/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 3fa6d6f3359de88564716fa8ab2de516681581b6af0c2476492984085126509c

build:
  number: 0
  noarch: python
  script:
    - cd dist && {{ PYTHON }} -m pip install . -vv
    - |-
      {{ PYTHON }} -c "(__import__('pathlib').Path(__import__('site').getsitepackages()[0]) / 'LICENSE').unlink()"

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6,<4.0
  run:
    - python >=3.6,<4.0
    # from poetry-generated setup.py
    - packageurl-python >=0.9
    - setuptools >=47.0.0
    - toml >=0.10.0,<0.11.0
    - types-setuptools >=57.0.0
    - types-toml >=0.10.0,<0.11.0
    # :python_version < "3.8"
    - importlib-metadata >=3.4
    - typing-extensions >=3.10,<4.0

test:
  source_files:
    - src/tests
    - src/cyclonedx/schema
  imports:
    - cyclonedx
  commands:
    - pip check
    - cd src/tests
    - pytest -vv --cov cyclonedx --cov-fail-under 90 --cov-report term-missing:skip-covered --no-cov-on-fail
  requires:
    - jsonschema >=4.2.1
    - lxml >=4.7.0
    - pip
    - pytest-cov
    - tox

about:
  home: https://github.com/CycloneDX/cyclonedx-python-lib
  summary: A library for producing CycloneDX SBOM (Software Bill of Materials) files.
  license: Apache-2.0
  license_file: dist/LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
